In [1]:
import pandas as pd
import os

# Full path to CSV file inside /content/sample_data
file_path = '/content/sample_data/california_housing_train.csv'

# Check if file exists
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("✅ File loaded successfully!\n")

    # Display full DataFrame (optional - not for large datasets)
    print(df)

    # Show first 5 and last 5 rows
    print("\n🔹 First 5 rows:")
    print(df.head())

    print("\n🔹 Last 5 rows:")
    print(df.tail())

    # Inspect DataFrame
    print("\n🔹 Shape of DataFrame (rows, columns):")
    print(df.shape)

    print("\n🔹 Info:")
    print(df.info())

    print("\n🔹 Summary statistics:")
    print(df.describe())

    # Selecting columns
    print("\n🔹 Single column: 'median_income'")
    print(df['median_income'])

    print("\n🔹 Multiple columns: ['housing_median_age', 'median_house_value']")
    print(df[['housing_median_age', 'median_house_value']])

    # Filtering rows
    print("\n🔹 Filter where median_income > 10:")
    print(df[df['median_income'] > 10])

    # Adding a new column
    df['income_plus_age'] = df['median_income'] + df['housing_median_age']

    # Dropping columns
    df = df.drop('total_rooms', axis=1)  # drop a single column
    df = df.drop(['population', 'households'], axis=1)  # drop multiple columns

    # Handling missing values
    print("\n🔹 Missing value count per column:")
    print(df.isnull().sum())

    df = df.dropna()  # Drop rows with missing values
    df = df.fillna(0)  # Fill any remaining with 0

    # Save to Excel
    df.to_excel('output.xlsx', index=False)
    print("\n✅ Data saved to 'output.xlsx'")

else:
    print(f"❌ File not found at path: {file_path}")

✅ File loaded successfully!

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

🔹 First 5 rows:
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0

🔹 Last 5 rows:
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

🔹 Shape of DataFrame (rows, columns):
(17000, 9)

🔹 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB
None

🔹 Summary statistics:
          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

🔹 Single column: 'median_income'
0        1.4936
1        1.8200
2        1.6509
3        3.1917
4        1.9250
          ...
16995    2.3571
16996    2.5179
16997    3.0313
16998    1.9797
16999    3.0147
Name: median_income, Length: 17000, dtype: float64

🔹 Multiple columns: ['housing_median_age', 'median_house_value']
       housing_median_age  median_house_value
0                    15.0             66900.0
1                    19.0             80100.0
2                    17.0             85700.0
3                    14.0             73400.0
4                    20.0             65500.0
...                   ...                 ...
16995                52.0            111400.0
16996                36.0             79000.0
16997                17.0            103600.0
16998                19.0             85800.0
16999                52.0             94600.0

[17000 rows x 2 columns]

🔹 Filter where median_income > 10:
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
172      -116.26     33.65                 3.0       7437.0          1222.0
698      -117.05     33.01                17.0       3430.0           425.0
818      -117.07     32.91                 5.0       2234.0           256.0
1443     -117.19     34.03                20.0        856.0           124.0
1528     -117.21     33.03                20.0       3370.0           433.0
...          ...       ...                 ...          ...             ...
16262    -122.49     37.79                52.0       2488.0           281.0
16309    -122.50     37.79                52.0          8.0             1.0
16357    -122.52     37.92                24.0        421.0            64.0
16386    -122.54     37.96                44.0       1552.0           204.0
16419    -122.56     37.94                36.0       2023.0           242.0

       population  households  median_income  median_house_value
172         574.0       302.0        10.2948            382400.0
698        1468.0       433.0        10.6186            429300.0
818         894.0       253.0        10.3354            477600.0
1443        395.0       145.0        10.8634            381800.0
1528       1020.0       408.0        11.0911            500001.0
...           ...         ...            ...                 ...
16262       805.0       295.0        10.7058            500001.0
16309        13.0         1.0        15.0001            500001.0
16357       163.0        75.0        14.5833            500001.0
16386       596.0       208.0        10.1290            500001.0
16419       653.0       241.0        10.6272            500001.0

[259 rows x 9 columns]

🔹 Missing value count per column:
longitude             0
latitude              0
housing_median_age    0
total_bedrooms        0
median_income         0
median_house_value    0
income_plus_age       0
dtype: int64

✅ Data saved to 'output.xlsx'